export const DEFAULT_ACCESS_TOKEN_EXPIRATION = '15m';
export const DEFAULT_REFRESH_TOKEN_EXPIRATION = '30d';
export const DEFAULT_VERIFICATION_TOKEN_EXPIRATION_HOURS = 24;
export const DEFAULT_PASSWORD_RESET_TOKEN_EXPIRATION_HOURS = 1;
export const DEFAULT_MAX_LOGIN_ATTEMPTS = 5;
export const DEFAULT_LOCKOUT_DURATION_MINUTES = 15;
export const MIN_PASSWORD_LENGTH = 8;
